import ACTION_PREFIX from './_actionPrefixes';
import * as COIN_API from '../../api/coinApi.api';

const PREFIX = ACTION_PREFIX.API;

export const ACTIONS = {
  UPDATE_COINAPI_LIMIT_INFO: `${PREFIX}UPDATE_COINAPI_LIMIT_INFO`,

  FETCH_COINAPI_BTC_USD_CHART_DATA: `${PREFIX}FETCH_COINAPI_BTC_USD_CHART_DATA`,
  FETCH_COINAPI_BTC_USD_CHART_DATA_SUCCESS: `${PREFIX}FETCH_COINAPI_BTC_USD_CHART_DATA_SUCCESS`,
  FETCH_COINAPI_BTC_USD_CHART_DATA_FAILURE: `${PREFIX}FETCH_COINAPI_BTC_USD_CHART_DATA_FAILURE`,

  FETCH_ALL_ASSETS: `${PREFIX}FETCH_ALL_ASSETS`,
  FETCH_ALL_ASSETS_SUCCESS: `${PREFIX}FETCH_ALL_ASSETS_SUCCESS`,
  FETCH_ALL_ASSETS_FAILURE: `${PREFIX}FETCH_ALL_ASSETS_FAILURE`,

  FETCH_ALL_SYMBOLS: `${PREFIX}FETCH_ALL_SYMBOLS`,
  FETCH_ALL_SYMBOLS_SUCCESS: `${PREFIX}FETCH_ALL_SYMBOLS_SUCCESS`,
  FETCH_ALL_SYMBOLS_FAILURE: `${PREFIX}FETCH_ALL_SYMBOLS_FAILURE`,

  FETCH_HISTORICAL_CHART_DATA: `${PREFIX}FETCH_HISTORICAL_CHART_DATA`,
  FETCH_HISTORICAL_CHART_DATA_SUCCESS: `${PREFIX}FETCH_HISTORICAL_CHART_DATA_SUCCESS`,
  FETCH_HISTORICAL_CHART_DATA_FAILURE: `${PREFIX}FETCH_HISTORICAL_CHART_DATA_FAILURE`,

  FETCH_LATEST_CHART_DATA: `${PREFIX}FETCH_LATEST_CHART_DATA`,
  FETCH_LATEST_CHART_DATA_SUCCESS: `${PREFIX}FETCH_LATEST_CHART_DATA_SUCCESS`,
  FETCH_LATEST_CHART_DATA_FAILURE: `${PREFIX}FETCH_LATEST_CHART_DATA_FAILURE`,

  FETCH_ALL_OHCLV_PERIODS: `${PREFIX}FETCH_ALL_OHCLV_PERIODS`,
  FETCH_ALL_OHCLV_PERIODS_SUCCESS: `${PREFIX}FETCH_ALL_OHCLV_PERIODS_SUCCESS`,
  FETCH_ALL_OHCLV_PERIODS_FAILURE: `${PREFIX}FETCH_ALL_OHCLV_PERIODS_FAILURE`,

  INCLUDE_PORTFOLIO_ASSETS: `${PREFIX}INCLUDE_PORTFOLIO_ASSETS`,

};


export function fetchLatestChartData (payload) {
  return {
    type: ACTIONS.FETCH_LATEST_CHART_DATA,
    payload,
  };
}
export function fetchHistoricalChartData (payload) {
  return {
    type: ACTIONS.FETCH_HISTORICAL_CHART_DATA,
    payload,
  };
}
export function fetchAllOhclvPeriods () {
  return {
    type: ACTIONS.FETCH_ALL_OHCLV_PERIODS,
    payload: null,
  };
}


export function fetchAllAssets () {
  return {
    type: ACTIONS.FETCH_ALL_ASSETS,
    payload: null,
  };
}
export function fetchAllSymbols () {
  return {
    type: ACTIONS.FETCH_ALL_SYMBOLS,
    payload: null,
  };
}

// export function includePortfolioAssets (portfolioAssets) {
//   return {
//     type: ACTIONS.INCLUDE_PORTFOLIO_ASSETS,
//     payload: {
//       portfolioAssets,
//     },
//   };
// }
export function fetchLatestBtcUsdData (latestDate) {
  return {
    type: ACTIONS.FETCH_COINAPI_BTC_USD_CHART_DATA,
    payload: {
      latestDate,
    },
  };
}
