import ACTION_PREFIX from '../_actionPrefixes';

const PREFIX = ACTION_PREFIX.DATABASE;

export const ACTIONS = {
  FETCH_SAVED_BTC_USD_DATA: `${PREFIX}FETCH_SAVED_BTC_USD_DATA`,
  FETCH_SAVED_BTC_USD_DATA_SUCCESS: `${PREFIX}FETCH_SAVED_BTC_USD_DATA_SUCCESS`,
  FETCH_SAVED_BTC_USD_DATA_FAILURE: `${PREFIX}FETCH_SAVED_BTC_USD_DATA_FAILURE`,

  CREATE_SAVED_BTC_USD_DATA: `${PREFIX}CREATE_SAVED_BTC_USD_DATA`,
  CREATE_SAVED_BTC_USD_DATA_SUCCESS: `${PREFIX}CREATE_SAVED_BTC_USD_DATA_SUCCESS`,
  CREATE_SAVED_BTC_USD_DATA_FAILURE: `${PREFIX}CREATE_SAVED_BTC_USD_DATA_FAILURE`,

};


