import ACTION_PREFIX from '../_actionPrefixes';

const PREFIX = ACTION_PREFIX.DATABASE;

export const ACTIONS = {
  FETCH_PORTFOLIO_1: `${PREFIX}FETCH_PORTFOLIO_1`,
  FETCH_PORTFOLIO_1_SUCCESS: `${PREFIX}FETCH_PORTFOLIO_1_SUCCESS`,
  FETCH_PORTFOLIO_1_FAILURE: `${PREFIX}FETCH_PORTFOLIO_1_FAILURE`,
  FETCH_PORTFOLIO_2: `${PREFIX}FETCH_PORTFOLIO_2`,
  FETCH_PORTFOLIO_2_SUCCESS: `${PREFIX}FETCH_PORTFOLIO_2_SUCCESS`,
  FETCH_PORTFOLIO_2_FAILURE: `${PREFIX}FETCH_PORTFOLIO_2_FAILURE`,

  FETCH_ALL_PORTFOLIOS: `${PREFIX}FETCH_ALL_PORTFOLIOS`,
  FETCH_ALL_PORTFOLIOS_SUCCESS: `${PREFIX}FETCH_ALL_PORTFOLIOS_SUCCESS`,
  FETCH_ALL_PORTFOLIOS_FAILURE: `${PREFIX}FETCH_ALL_PORTFOLIOS_FAILURE`,

  CREATE_PORTFOLIO: `${PREFIX}CREATE_PORTFOLIO`,
  CREATE_PORTFOLIO_SUCCESS: `${PREFIX}CREATE_PORTFOLIO_SUCCESS`,
  CREATE_PORTFOLIO_FAILURE: `${PREFIX}CREATE_PORTFOLIO_FAILURE`,

  UPDATE_PORTFOLIO: `${PREFIX}UPDATE_PORTFOLIO`,
  UPDATE_PORTFOLIO_SUCCESS: `${PREFIX}UPDATE_PORTFOLIO_SUCCESS`,
  UPDATE_PORTFOLIO_FAILURE: `${PREFIX}UPDATE_PORTFOLIO_FAILURE`,

  DELETE_PORTFOLIO: `${PREFIX}DELETE_PORTFOLIO`,
  DELETE_PORTFOLIO_SUCCESS: `${PREFIX}DELETE_PORTFOLIO_SUCCESS`,
  DELETE_PORTFOLIO_FAILURE: `${PREFIX}DELETE_PORTFOLIO_FAILURE`,

};


export function createPortfolio (payload) {
  return {
    type: ACTIONS.CREATE_PORTFOLIO,
    payload,
  };
}
export function updatePortfolio (payload) {
  return {
    type: ACTIONS.UPDATE_PORTFOLIO,
    payload,
  };
}
export function deletePortfolio (payload) {
  return {
    type: ACTIONS.DELETE_PORTFOLIO,
    payload,
  };
}
export function fetchAllPortfolios (payload) {
  return {
    type: ACTIONS.FETCH_ALL_PORTFOLIOS,
    payload,
  };
}
export function fetchPortfolio1 (payload) {
  return {
    type: ACTIONS.FETCH_PORTFOLIO_1,
    payload,
  };
}
export function fetchPortfolio2 (payload) {
  return {
    type: ACTIONS.FETCH_PORTFOLIO_2,
    payload,
  };
}
export function fetchBtcUsdChartData (payload) {
  return {
    type: ACTIONS.FETCH_COINAPI_BTC_USD_CHART_DATA,
    payload,
  };
}

