import ACTION_PREFIX from '../_actionPrefixes';

const PREFIX = ACTION_PREFIX.DATABASE;

export const ACTIONS = {
  FETCH_ALL_PORTFOLIO_ASSETS: `${PREFIX}FETCH_ALL_PORTFOLIO_ASSETS`,
  FETCH_ALL_PORTFOLIO_ASSETS_SUCCESS: `${PREFIX}FETCH_ALL_PORTFOLIO_ASSETS_SUCCESS`,
  FETCH_ALL_PORTFOLIO_ASSETS_FAILURE: `${PREFIX}FETCH_ALL_PORTFOLIO_ASSETS_FAILURE`,

  FETCH_PORTFOLIO_ASSETS: `${PREFIX}FETCH_PORTFOLIO_ASSETS`,
  FETCH_PORTFOLIO_ASSETS_SUCCESS: `${PREFIX}FETCH_PORTFOLIO_ASSETS_SUCCESS`,
  FETCH_PORTFOLIO_ASSETS_FAILURE: `${PREFIX}FETCH_PORTFOLIO_ASSETS_FAILURE`,

  FETCH_PORTFOLIO_ASSET: `${PREFIX}FETCH_PORTFOLIO_ASSET`,
  FETCH_PORTFOLIO_ASSET_SUCCESS: `${PREFIX}FETCH_PORTFOLIO_ASSET_SUCCESS`,
  FETCH_PORTFOLIO_ASSET_FAILURE: `${PREFIX}FETCH_PORTFOLIO_ASSET_FAILURE`,

  UPDATE_PORTFOLIO_ASSET: `${PREFIX}UPDATE_PORTFOLIO_ASSET`,
  UPDATE_PORTFOLIO_ASSET_SUCCESS: `${PREFIX}UPDATE_PORTFOLIO_ASSET_SUCCESS`,
  UPDATE_PORTFOLIO_ASSET_FAILURE: `${PREFIX}UPDATE_PORTFOLIO_ASSET_FAILURE`,

  CREATE_PORTFOLIO_ASSET: `${PREFIX}CREATE_PORTFOLIO_ASSET`,
  CREATE_PORTFOLIO_ASSET_SUCCESS: `${PREFIX}CREATE_PORTFOLIO_ASSET_SUCCESS`,
  CREATE_PORTFOLIO_ASSET_FAILURE: `${PREFIX}CREATE_PORTFOLIO_ASSET_FAILURE`,

  DELETE_PORTFOLIO_ASSET: `${PREFIX}DELETE_PORTFOLIO_ASSET`,
  DELETE_PORTFOLIO_ASSET_SUCCESS: `${PREFIX}DELETE_PORTFOLIO_ASSET_SUCCESS`,
  DELETE_PORTFOLIO_ASSET_FAILURE: `${PREFIX}DELETE_PORTFOLIO_ASSET_FAILURE`,

};


export function fetchAllPortfolioAssets () {
  return {
    type: ACTIONS.FETCH_ALL_PORTFOLIO_ASSETS,
    payload: null,
  };
}
export function fetchPortfolioAssets (portfolioId) {
  return {
    type: ACTIONS.FETCH_PORTFOLIO_ASSETS,
    payload: {
      portfolioId,
    },
  };
}
export function fetchPortfolioAsset (portfolioAssetId) {
  return {
    type: ACTIONS.FETCH_PORTFOLIO_ASSET,
    payload: {
      portfolioAssetId,
    },
  };
}
export function updatePortfolioAsset (portfolioAsset) {
  return {
    type: ACTIONS.UPDATE_PORTFOLIO_ASSET,
    payload: {
      portfolioAsset,
    },
  };
}
export function createPortfolioAsset (portfolioAsset) {
  return {
    type: ACTIONS.CREATE_PORTFOLIO_ASSET,
    payload: {
      portfolioAsset,
    },
  };
}
export function deletePortfolioAsset (portfolioAsset) {
  return {
    type: ACTIONS.DELETE_PORTFOLIO_ASSET,
    payload: {
      portfolioAsset,
    },
  };
}
